### ISSUE TITLE
sgRNA_library_evaluation_cmd.R does not surpport user specified PAMs?

### ISSUE THREAD

**Issue by taosheng19** [vincentdebakker/CRISPRi-seq#4] opened 2022-10-11 08:18 UTC
Hi Vincent, 
When I run the rscritp "sgRNA_library_evaluation_cmd.R" with a specified PAM (i.e., NNAGAAG), the script report the following error: 
---------------------
Using refseq data base. (Please use GCA accession for genbank and GCF for refseq.)
Warning messages:
1: In rm(genome_gb_ls, genome_txt) : object 'genome_gb_ls' not found
2: In rm(genome_gb_ls, genome_txt) : object 'genome_txt' not found

Starting at: Tue Oct 11 15:22:29 2022

Alignment matrix generation ended on: Tue Oct 11 15:22:35 2022
Ended on: Tue Oct 11 15:22:35 2022
Error in data.frame(sgRNA_name = names(gRNAs[sort(unique(sg_hits[, 1]))]),  : 
  arguments imply differing number of rows: 100, 99
Execution halted
--------------------

I tried the script with the library you provided (sgRNA-library_spn-D39V.csv), it works fine. Then I tried my library with default PAM, it worked. So, it seems so problem with the script dealing with PAM other than defaults.

**Comment by vincentdebakker** [comment] 2022-10-19 16:41
Hi, 

I just pushed an update to my github. Could reproduce the problem, and it works for me now. Let me know if it's resolved!
Otherwise I'll close this issue in a week's time. 

Cheers,
Vincent

**Comment by vincentdebakker** [comment] 2022-10-26 14:45
Considering this solved, will close the issue now.

**Closed as completed by vincentdebakker** 2022-10-26 14:45 UTC
